[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "bgnew"
version = "2.0.0"
description = "Xhunta AI Image Background Remover API"
requires-python = ">=3.11"

dependencies = [
    "fastapi[standard]",
    "fastapi-cli==0.0.27",
    "fastapi-cloud-cli==0.20.0",
    "uvicorn==0.49.0",
    "python-multipart",
    "Pillow",
    "rembg==2.0.76",
    "onnxruntime",
    "psutil",
]

[tool.fastapi]
entrypoint = "main:app"

[tool.setuptools]
py-modules = ["main"]